### ISSUE TITLE
스프링부트 도커파일 만들기 

### ISSUE THREAD

**Issue by teang1995** [teang1995/movie_review_project#4]
스프링부트가 돌아가는 도커컨테이너 제작을 위한 도커파일을 만들어보겠습니다.

저는 m1 mac air에서 했는데.. 윈도우나 리눅스에서도 돌아가길 간절히 바라며 작성해보겠습니다.

**Comment by teang1995** [comment]
도커 테스트 환경
1. ytlim 브랜치로 풀
(`git pull movie_review_project` 돼있을 것 같아서 괄호)
cd movie_review_project
git branch ytlim
git checkout ytlim
git pull

2. docker image build
```Dockerfile
FROM openjdk:8-jdk-alpine

EXPOSE 8080
```
`docker build -t spring_docker_test .`

4. run docker container
유의 사항 :  `8080` 포트 열어두기~!
`docker run -itd -v $(pwd):/code -p 8080:8080 --name spring_test spring_docker_test`

5. exec. docker
`docker exec -it spring_test /bin/sh`

6. build gradlew
`cd code`
`./gradlew build`

하면 될 줄 알았는데 에러가 났다.. 추후 수정 예정

**Comment by teang1995** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/23451721/162559282-f6ede9de-b2e4-4191-a33c-9dda7c9d2aff.png">
와 같은 에러가 발생했다. 내가 밖에서 짠 코드와 도커 이미지의 자바 버전이 맞지 않는 걸까?

**Comment by teang1995** [comment]
해당 도커파일의 jdk 버전이 8이어서 그랬다. 11로 변경하여 실행하니 스프링이 잘 띄워지는 것을 확인.

**Comment by teang1995** [comment]
`~/run_server.sh` 를 실행하기만 하면 추가적인 명령어 없이 서버 실행되도록 만듦.

**Comment by teang1995** [comment]
git clone 한 후, 아무 조작 없이 bash파일 실행하여 서버 작동되는 것까지 확인.
README에 `git clone`이후 서버 실행과정까지 간략하게 추가.

**Comment by jjongguet4u** [comment]
readme.md 파일에 나와있는대로 진행하였으나 에러나서 올립니다.
개발환경은 M1 mac air입니다. 
sh run_server.sh
Unable to find image 'spring_docker_test:v0.1' locally
docker: Error response from daemon: pull access denied for spring_docker_test, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

**Comment by jjongguet4u** [comment]
docker login <- 을 실행하여 로그인 한 이후에도 동일한 에러가 발생합니다.
이미지의 username과 dockerhub에 가입된 ID가 일치하지않을때 생기는 에러로 확인됩니다
